# Model Selection and Final Evaluation

Tujuan:

Notebook ini bertujuan mengevaluasi dan membandingkan seluruh model yang telah dikembangkan pada tahap sebelumnya untuk menentukan model yang paling sesuai digunakan sebagai production model.

Evaluasi dilakukan berdasarkan hasil eksperimen:

- Baseline Modeling
- Historical Modeling
- Elo Modeling
- Advanced Modeling

Notebook ini tidak melakukan pelatihan model baru. Seluruh evaluasi menggunakan metrics dan model yang telah dihasilkan pada notebook sebelumnya.

## 1. Import
Tujuan: Library yang digunakan pada tahap ini berfokus pada pengolahan, visualisasi, dan evaluasi hasil eksperimen yang telah tersimpan.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# Project paths
REPORTS_DIR = Path("../reports")
MODELS_DIR = Path("../models")

## 2. Load Model Metrics 
Hasil evaluasi dari seluruh tahap modeling sebelumnya disimpan dalam file CSV terpisah. Pada tahap ini seluruh metrics tersebut akan dimuat untuk membentuk satu benchmark hasil eksperimen.

In [2]:
baseline_metrics = pd.read_csv(
    REPORTS_DIR / "baseline_metrics.csv"
)

historical_metrics = pd.read_csv(
    REPORTS_DIR / "historical_metrics.csv"
)

elo_metrics = pd.read_csv(
    REPORTS_DIR / "elo_metrics.csv"
)

advanced_metrics = pd.read_csv(
    REPORTS_DIR / "advanced_metrics.csv"
)

display(baseline_metrics)
display(historical_metrics)
display(elo_metrics)
display(advanced_metrics)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.572975   0.521363  0.572975  0.509571
1        Random Forest  0.508445   0.470924  0.508445  0.478398

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.580459   0.526805  0.580459  0.520899
1        Random Forest  0.546677   0.495492  0.546677  0.471682

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.593203   0.558947  0.593203  0.512776
1        Random Forest  0.576919   0.527102  0.576919  0.509791

      Model  Accuracy  Precision    Recall  F1 Score
0   XGBoost  0.591888   0.537479  0.591888  0.521782
1  LightGBM  0.591686   0.536832  0.591686  0.523613

## 3. Combine Model Metrics
Hasil evaluasi dari setiap tahap modeling akan digabungkan menjadi satu tabel benchmark. Informasi mengenai tahap eksperimen (*stage*) ditambahkan agar setiap model dapat diidentifikasi berdasarkan feature set dan algoritma yang digunakan.

In [3]:
# Add experiment stage
baseline_metrics["Stage"] = "Baseline"
historical_metrics["Stage"] = "Historical"
elo_metrics["Stage"] = "Elo"
advanced_metrics["Stage"] = "Advanced"

In [6]:
all_metrics = pd.concat(
    [
        baseline_metrics,
        historical_metrics,
        elo_metrics,
        advanced_metrics
    ],
    ignore_index=True
)

all_metrics = all_metrics[
    [
        "Stage",
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
]


display(all_metrics)

        Stage                Model  Accuracy  Precision    Recall  F1 Score
0    Baseline  Logistic Regression  0.572975   0.521363  0.572975  0.509571
1    Baseline        Random Forest  0.508445   0.470924  0.508445  0.478398
2  Historical  Logistic Regression  0.580459   0.526805  0.580459  0.520899
3  Historical        Random Forest  0.546677   0.495492  0.546677  0.471682
4         Elo  Logistic Regression  0.593203   0.558947  0.593203  0.512776
5         Elo        Random Forest  0.576919   0.527102  0.576919  0.509791
6    Advanced              XGBoost  0.591888   0.537479  0.591888  0.521782
7    Advanced             LightGBM  0.591686   0.536832  0.591686  0.523613

### Leaderboard

In [7]:
leaderboard = all_metrics.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

display(leaderboard)

        Stage                Model  Accuracy  Precision    Recall  F1 Score
0         Elo  Logistic Regression  0.593203   0.558947  0.593203  0.512776
1    Advanced              XGBoost  0.591888   0.537479  0.591888  0.521782
2    Advanced             LightGBM  0.591686   0.536832  0.591686  0.523613
3  Historical  Logistic Regression  0.580459   0.526805  0.580459  0.520899
4         Elo        Random Forest  0.576919   0.527102  0.576919  0.509791
5    Baseline  Logistic Regression  0.572975   0.521363  0.572975  0.509571
6  Historical        Random Forest  0.546677   0.495492  0.546677  0.471682
7    Baseline        Random Forest  0.508445   0.470924  0.508445  0.478398